'use strict';

function mobilePageHtml() {
  return `<!doctype html><html lang="pt-BR"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1,viewport-fit=cover"><title>Sistema Financeiro</title><style>
:root{font-family:Inter,system-ui,-apple-system,BlinkMacSystemFont,"Segoe UI",sans-serif;color:#172033;background:#f4f6fb}*{box-sizing:border-box}body{margin:0}.shell{max-width:900px;margin:auto;padding:18px}.top{display:flex;justify-content:space-between;align-items:center;margin-bottom:18px}.brand{font-weight:800}.brand small{display:block;color:#7c879a;font-weight:500}.card{background:white;border:1px solid #e2e7f0;border-radius:14px;padding:16px;margin-bottom:12px}.login{max-width:420px;margin:12vh auto}.login input{width:100%;font-size:24px;letter-spacing:.2em;text-align:center;padding:12px;border:1px solid #ccd4df;border-radius:10px}.btn{border:0;border-radius:10px;padding:11px 14px;background:#665cf6;color:white;font-weight:800;width:100%;margin-top:10px}.btn.ghost{width:auto;background:#edf0f6;color:#4c5870}.metrics{display:grid;grid-template-columns:repeat(2,minmax(0,1fr));gap:10px}.metric{background:white;border:1px solid #e2e7f0;border-radius:12px;padding:14px}.metric span{display:block;color:#7c879a;font-size:12px}.metric strong{display:block;margin-top:6px;font-size:20px}.row{display:flex;justify-content:space-between;gap:12px;padding:11px 0;border-bottom:1px solid #edf0f4}.row:last-child{border-bottom:0}.row small{display:block;color:#7c879a}.danger{color:#b93636}.alert{border-left:4px solid #f59e0b;padding-left:12px}.alert.critical{border-left-color:#dc2626}.tabs{display:flex;gap:8px;overflow:auto;margin:14px 0}.tabs button{border:0;background:#e9edf5;color:#59657a;border-radius:9px;padding:9px 12px;font-weight:700}.hidden{display:none}.empty{color:#8791a3;text-align:center;padding:18px}@media(min-width:700px){.metrics{grid-template-columns:repeat(4,1fr)}}
</style></head><body><div class="shell"><div id="login" class="card login"><div class="brand">ArtiSys<small>Sistema Financeiro · acesso local</small></div><p>Digite o código de pareamento exibido no computador principal.</p><input id="code" inputmode="numeric" maxlength="6" placeholder="000000"><button class="btn" id="pair">Conectar</button><p id="loginError" class="danger"></p></div><div id="app" class="hidden"><div class="top"><div class="brand">Sistema Financeiro<small>Rede local</small></div><button class="btn ghost" id="logout">Sair</button></div><div id="metrics" class="metrics"></div><div class="tabs"><button data-tab="alerts">Alertas</button><button data-tab="accounts">Contas</button><button data-tab="payables">A pagar</button><button data-tab="receivables">A receber</button></div><div id="content"></div></div></div><script>
const $=s=>document.querySelector(s);const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));const brl=c=>new Intl.NumberFormat('pt-BR',{style:'currency',currency:'BRL'}).format((Number(c)||0)/100);let token=sessionStorage.getItem('lan-token')||'';let cache={};
async function api(path,options={}){const headers={...(options.headers||{})};if(token)headers.authorization='Bearer '+token;if(options.body&&!headers['content-type'])headers['content-type']='application/json';const r=await fetch(path,{...options,headers});const body=await r.json().catch(()=>({}));if(!r.ok)throw new Error(body.error||'Falha na comunicação');return body}
async function pair(){try{const result=await api('/api/pair',{method:'POST',body:JSON.stringify({code:$('#code').value.trim()})});token=result.token;sessionStorage.setItem('lan-token',token);showApp();await refresh()}catch(e){$('#loginError').textContent=e.message}}
function showApp(){if(token){$('#login').classList.add('hidden');$('#app').classList.remove('hidden')}else{$('#app').classList.add('hidden');$('#login').classList.remove('hidden')}}
async function refresh(){try{const [dashboard,alerts,accounts,payables,receivables]=await Promise.all([api('/api/dashboard'),api('/api/alerts'),api('/api/accounts'),api('/api/entries?kind=PAYABLE'),api('/api/entries?kind=RECEIVABLE')]);cache={dashboard,alerts,accounts,payables,receivables};$('#metrics').innerHTML=[['Saldo total',dashboard.cards.totalBalanceCents],['A receber',dashboard.cards.receivableOpenCents],['A pagar',dashboard.cards.payableOpenCents],['Vencidos',(dashboard.cards.overduePayableCents||0)+(dashboard.cards.overdueReceivableCents||0)]].map(([l,v])=>'<div class="metric"><span>'+esc(l)+'</span><strong>'+brl(v)+'</strong></div>').join('');render('alerts')}catch(e){if(/auth|token|unauthorized/i.test(e.message)){token='';sessionStorage.removeItem('lan-token');showApp()}else $('#content').innerHTML='<div class="card danger">'+esc(e.message)+'</div>'}}
function render(tab){let html='';if(tab==='alerts'){const a=cache.alerts||[];html=a.length?a.map(x=>'<div class="card alert '+(x.severity==='CRITICAL'?'critical':'')+'"><strong>'+esc(x.title)+'</strong><div>'+esc(x.body)+'</div><small>'+esc(x.type)+'</small><button class="btn ghost" onclick="ack(\''+esc(x.key)+'\')">Marcar lido</button></div>').join(''):'<div class="card empty">Sem alertas.</div>'}else if(tab==='accounts'){html='<div class="card">'+(cache.accounts||[]).map(x=>'<div class="row"><div><strong>'+esc(x.name)+'</strong><small>'+esc(x.type)+'</small></div><strong>'+brl(x.balanceCents)+'</strong></div>').join('')+'</div>'}else{const rows=tab==='payables'?cache.payables:cache.receivables;html='<div class="card">'+((rows||[]).length?(rows||[]).map(x=>'<div class="row"><div><strong>'+esc(x.description)+'</strong><small>'+esc(x.dueAt)+' · '+esc(x.status)+'</small></div><strong class="'+(x.isOverdue?'danger':'')+'">'+brl(x.openCents)+'</strong></div>').join(''):'<div class="empty">Nenhum lançamento.</div>')+'</div>'}$('#content').innerHTML=html}
async function ack(key){await api('/api/alerts/'+encodeURIComponent(key)+'/ack',{method:'POST',body:JSON.stringify({state:'READ'})});cache.alerts=await api('/api/alerts');render('alerts')}
window.ack=ack;$('#pair').addEventListener('click',pair);$('#logout').addEventListener('click',()=>{token='';sessionStorage.removeItem('lan-token');showApp()});document.querySelectorAll('[data-tab]').forEach(b=>b.addEventListener('click',()=>render(b.dataset.tab)));showApp();if(token)refresh();
</script></body></html>`;
}

module.exports = { mobilePageHtml };
