const { contextBridge, ipcRenderer } = require('electron');

contextBridge.exposeInMainWorld('financeiroPlanning', {
  listCostCenters: (token, filters) => ipcRenderer.invoke('planning:cost-centers:list', token, filters),
  saveCostCenter: (token, input) => ipcRenderer.invoke('planning:cost-centers:save', token, input),
  listTags: (token, filters) => ipcRenderer.invoke('planning:tags:list', token, filters),
  saveTag: (token, input) => ipcRenderer.invoke('planning:tags:save', token, input),
  getAllocations: (token, entryId) => ipcRenderer.invoke('planning:allocations:get', token, entryId),
  setAllocations: (token, entryId, allocations) => ipcRenderer.invoke('planning:allocations:set', token, entryId, allocations),
  getEntryTags: (token, entryId) => ipcRenderer.invoke('planning:entry-tags:get', token, entryId),
  setEntryTags: (token, entryId, tagIds) => ipcRenderer.invoke('planning:entry-tags:set', token, entryId, tagIds),
  listScenarios: (token, filters) => ipcRenderer.invoke('planning:scenarios:list', token, filters),
  saveScenario: (token, input) => ipcRenderer.invoke('planning:scenarios:save', token, input),
  listBudgets: (token, filters) => ipcRenderer.invoke('planning:budgets:list', token, filters),
  saveBudget: (token, input) => ipcRenderer.invoke('planning:budgets:save', token, input),
  compareBudget: (token, filters) => ipcRenderer.invoke('planning:budgets:compare', token, filters),
  listGoals: (token, filters) => ipcRenderer.invoke('planning:goals:list', token, filters),
  saveGoal: (token, input) => ipcRenderer.invoke('planning:goals:save', token, input),
  listAttachments: (token, entryId) => ipcRenderer.invoke('planning:attachments:list', token, entryId),
  addAttachment: (token, entryId, input) => ipcRenderer.invoke('planning:attachments:add', token, entryId, input),
  reviewAttachment: (token, id) => ipcRenderer.invoke('planning:attachments:review', token, id),
  listApprovalPolicies: (token, filters) => ipcRenderer.invoke('planning:approval-policies:list', token, filters),
  saveApprovalPolicy: (token, input) => ipcRenderer.invoke('planning:approval-policies:save', token, input),
  listApprovals: (token, filters) => ipcRenderer.invoke('planning:approvals:list', token, filters),
  requestApproval: (token, input) => ipcRenderer.invoke('planning:approvals:request', token, input),
  decideApproval: (token, requestId, input) => ipcRenderer.invoke('planning:approvals:decide', token, requestId, input),
  runBulk: (token, input) => ipcRenderer.invoke('planning:bulk', token, input),
  projection: (token, input) => ipcRenderer.invoke('planning:projection', token, input),
});
