const { contextBridge, ipcRenderer } = require('electron');

contextBridge.exposeInMainWorld('financeiro', {
  system: { health: () => ipcRenderer.invoke('system:health') },
  auth: {
    needsBootstrap: () => ipcRenderer.invoke('auth:needs-bootstrap'),
    bootstrap: (input) => ipcRenderer.invoke('auth:bootstrap', input),
    login: (login, password) => ipcRenderer.invoke('auth:login', login, password),
    session: (token) => ipcRenderer.invoke('auth:session', token),
    logout: (token) => ipcRenderer.invoke('auth:logout', token),
    listUsers: (token) => ipcRenderer.invoke('auth:users:list', token),
    createUser: (token, input) => ipcRenderer.invoke('auth:users:create', token, input),
    setUserActive: (token, userId, active) => ipcRenderer.invoke('auth:users:set-active', token, userId, active),
  },
  finance: {
    listAccounts: (token, filters) => ipcRenderer.invoke('finance:accounts:list', token, filters),
    createAccount: (token, input) => ipcRenderer.invoke('finance:accounts:create', token, input),
    listEntries: (token, filters) => ipcRenderer.invoke('finance:entries:list', token, filters),
    createEntry: (token, input) => ipcRenderer.invoke('finance:entries:create', token, input),
    settleEntry: (token, entryId, input) => ipcRenderer.invoke('finance:entries:settle', token, entryId, input),
    reverseSettlement: (token, settlementId, reason) => ipcRenderer.invoke('finance:settlements:reverse', token, settlementId, reason),
    cancelEntry: (token, entryId, reason) => ipcRenderer.invoke('finance:entries:cancel', token, entryId, reason),
    summary: (token, filters) => ipcRenderer.invoke('finance:summary', token, filters),
  },
  cashflow: {
    listMovements: (token, filters) => ipcRenderer.invoke('cashflow:movements:list', token, filters),
    createMovement: (token, input) => ipcRenderer.invoke('cashflow:movements:create', token, input),
    transfer: (token, input) => ipcRenderer.invoke('cashflow:transfer', token, input),
    balances: (token, filters) => ipcRenderer.invoke('cashflow:balances', token, filters),
    summary: (token, filters) => ipcRenderer.invoke('cashflow:summary', token, filters),
  },
  analytics: {
    dre: (token, filters) => ipcRenderer.invoke('analytics:dre', token, filters),
    indicators: (token, filters) => ipcRenderer.invoke('analytics:indicators', token, filters),
    dashboard: (token, filters) => ipcRenderer.invoke('analytics:dashboard', token, filters),
  },
  recurrence: {
    list: (token, filters) => ipcRenderer.invoke('recurrence:list', token, filters),
    create: (token, input) => ipcRenderer.invoke('recurrence:create', token, input),
    setActive: (token, id, active) => ipcRenderer.invoke('recurrence:set-active', token, id, active),
    generate: (token, asOf) => ipcRenderer.invoke('recurrence:generate', token, asOf),
  },
  alerts: {
    list: (token, filters) => ipcRenderer.invoke('alerts:list', token, filters),
    acknowledge: (token, alertKey, state) => ipcRenderer.invoke('alerts:ack', token, alertKey, state),
    listThresholds: (token) => ipcRenderer.invoke('alerts:thresholds:list', token),
    setThreshold: (token, accountId, thresholdCents, enabled) => ipcRenderer.invoke('alerts:thresholds:set', token, accountId, thresholdCents, enabled),
    saveInternal: (token, input) => ipcRenderer.invoke('alerts:internal:save', token, input),
  },
  reports: {
    financial: (token, filters) => ipcRenderer.invoke('reports:financial', token, filters),
    receipt: (token, settlementId) => ipcRenderer.invoke('reports:receipt', token, settlementId),
    csv: (token, filters) => ipcRenderer.invoke('reports:csv', token, filters),
    xlsx: (token, filters) => ipcRenderer.invoke('reports:xlsx', token, filters),
    savePdf: (token, filters) => ipcRenderer.invoke('reports:pdf', token, filters),
    print: (token, filters) => ipcRenderer.invoke('reports:print', token, filters),
    saveReceiptPdf: (token, settlementId) => ipcRenderer.invoke('reports:receipt-pdf', token, settlementId),
    printReceipt: (token, settlementId) => ipcRenderer.invoke('reports:receipt-print', token, settlementId),
  },
  backup: {
    list: (token, filters) => ipcRenderer.invoke('backup:list', token, filters),
    create: (token) => ipcRenderer.invoke('backup:create', token),
    verify: (token, filePath) => ipcRenderer.invoke('backup:verify', token, filePath),
    restoreSelect: (token) => ipcRenderer.invoke('backup:restore-select', token),
  },
  lan: {
    status: (token) => ipcRenderer.invoke('lan:status', token),
    configure: (token, input) => ipcRenderer.invoke('lan:configure', token, input),
    pairingCode: (token) => ipcRenderer.invoke('lan:pairing-code', token),
  },
  registry: {
    listCustomers: (token, filters) => ipcRenderer.invoke('registry:customers:list', token, filters),
    saveCustomer: (token, input) => ipcRenderer.invoke('registry:customers:save', token, input),
    setCustomerActive: (token, id, active) => ipcRenderer.invoke('registry:customers:set-active', token, id, active),
    listCreditors: (token, filters) => ipcRenderer.invoke('registry:creditors:list', token, filters),
    saveCreditor: (token, input) => ipcRenderer.invoke('registry:creditors:save', token, input),
    setCreditorActive: (token, id, active) => ipcRenderer.invoke('registry:creditors:set-active', token, id, active),
    listCategories: (token, filters) => ipcRenderer.invoke('registry:categories:list', token, filters),
    saveCategory: (token, input) => ipcRenderer.invoke('registry:categories:save', token, input),
    setCategoryActive: (token, id, active) => ipcRenderer.invoke('registry:categories:set-active', token, id, active),
  },
});
