const { contextBridge, ipcRenderer, webUtils } = require('electron');

contextBridge.exposeInMainWorld('financeiro', {
  system: { health: () => ipcRenderer.invoke('system:health') },
  auth: {
    needsBootstrap: () => ipcRenderer.invoke('auth:needs-bootstrap'),
    bootstrap: (input) => ipcRenderer.invoke('auth:bootstrap', input),
    login: (login, password) => ipcRenderer.invoke('auth:login', login, password),
    session: (token) => ipcRenderer.invoke('auth:session', token),
    logout: (token) => ipcRenderer.invoke('auth:logout', token),
    listUsers: (token) => ipcRenderer.invoke('auth:users:list', token),
    createUser: (token, input) => ipcRenderer.invoke('auth:users:create', token, input),
    setUserActive: (token, userId, active) => ipcRenderer.invoke('auth:users:set-active', token, userId, active),
  },
  finance: {
    listAccounts: (token, filters) => ipcRenderer.invoke('finance:accounts:list', token, filters),
    createAccount: (token, input) => ipcRenderer.invoke('finance:accounts:create', token, input),
    listEntries: (token, filters) => ipcRenderer.invoke('finance:entries:list', token, filters),
    createEntry: (token, input) => ipcRenderer.invoke('finance:entries:create', token, input),
    settleEntry: (token, entryId, input) => ipcRenderer.invoke('finance:entries:settle', token, entryId, input),
    reverseSettlement: (token, settlementId, reason) => ipcRenderer.invoke('finance:settlements:reverse', token, settlementId, reason),
    cancelEntry: (token, entryId, reason) => ipcRenderer.invoke('finance:entries:cancel', token, entryId, reason),
    summary: (token, filters) => ipcRenderer.invoke('finance:summary', token, filters),
  },
  statements: {
    preview: (token, input) => ipcRenderer.invoke('statements:preview', token, input),
    commit: (token, input) => ipcRenderer.invoke('statements:commit', token, input),
    list: (token, filters) => ipcRenderer.invoke('statements:list', token, filters),
    suggestTransfers: (token, filters) => ipcRenderer.invoke('statements:suggest-transfers', token, filters),
    suggestEntries: (token, filters) => ipcRenderer.invoke('statements:suggest-entries', token, filters),
    decision: (token, input) => ipcRenderer.invoke('statements:decision', token, input),
  },
  workspace: {
    list: (token, relativePath) => ipcRenderer.invoke('workspace:list', token, relativePath),
    tree: (token) => ipcRenderer.invoke('workspace:tree', token),
    search: (token, query) => ipcRenderer.invoke('workspace:search', token, query),
    listTrash: (token) => ipcRenderer.invoke('workspace:trash:list', token),
    preferences: (token) => ipcRenderer.invoke('workspace:preferences', token),
    setPreferences: (token, input) => ipcRenderer.invoke('workspace:preferences:set', token, input),
    createFolder: (token, parentPath, name) => ipcRenderer.invoke('workspace:create-folder', token, parentPath, name),
    createFile: (token, parentPath, name, content) => ipcRenderer.invoke('workspace:create-file', token, parentPath, name, content),
    importFiles: (token, targetPath) => ipcRenderer.invoke('workspace:import-select', token, targetPath),
    importDropped: (token, targetPath, files) => {
      const sourcePaths = Array.from(files || []).map((file) => webUtils.getPathForFile(file)).filter(Boolean);
      return ipcRenderer.invoke('workspace:import-paths', token, targetPath, sourcePaths);
    },
    rename: (token, relativePath, name) => ipcRenderer.invoke('workspace:rename', token, relativePath, name),
    move: (token, relativePath, targetPath) => ipcRenderer.invoke('workspace:move', token, relativePath, targetPath),
    copy: (token, relativePath, targetPath) => ipcRenderer.invoke('workspace:copy', token, relativePath, targetPath),
    trash: (token, relativePath) => ipcRenderer.invoke('workspace:trash', token, relativePath),
    restore: (token, id) => ipcRenderer.invoke('workspace:trash:restore', token, id),
    deleteForever: (token, id) => ipcRenderer.invoke('workspace:trash:delete', token, id),
    open: (token, relativePath) => ipcRenderer.invoke('workspace:open', token, relativePath),
    reveal: (token, relativePath) => ipcRenderer.invoke('workspace:reveal', token, relativePath),
  },
  cashflow: {
    listMovements: (token, filters) => ipcRenderer.invoke('cashflow:movements:list', token, filters),
    createMovement: (token, input) => ipcRenderer.invoke('cashflow:movements:create', token, input),
    transfer: (token, input) => ipcRenderer.invoke('cashflow:transfer', token, input),
    balances: (token, filters) => ipcRenderer.invoke('cashflow:balances', token, filters),
    summary: (token, filters) => ipcRenderer.invoke('cashflow:summary', token, filters),
  },
  analytics: {
    dre: (token, filters) => ipcRenderer.invoke('analytics:dre', token, filters),
    indicators: (token, filters) => ipcRenderer.invoke('analytics:indicators', token, filters),
    dashboard: (token, filters) => ipcRenderer.invoke('analytics:dashboard', token, filters),
  },
  recurrence: {
    list: (token, filters) => ipcRenderer.invoke('recurrence:list', token, filters),
    create: (token, input) => ipcRenderer.invoke('recurrence:create', token, input),
    setActive: (token, id, active) => ipcRenderer.invoke('recurrence:set-active', token, id, active),
    generate: (token, asOf) => ipcRenderer.invoke('recurrence:generate', token, asOf),
  },
  alerts: {
    list: (token, filters) => ipcRenderer.invoke('alerts:list', token, filters),
    acknowledge: (token, alertKey, state) => ipcRenderer.invoke('alerts:ack', token, alertKey, state),
    listThresholds: (token) => ipcRenderer.invoke('alerts:thresholds:list', token),
    setThreshold: (token, accountId, thresholdCents, enabled) => ipcRenderer.invoke('alerts:thresholds:set', token, accountId, thresholdCents, enabled),
    saveInternal: (token, input) => ipcRenderer.invoke('alerts:internal:save', token, input),
  },
  reports: {
    financial: (token, filters) => ipcRenderer.invoke('reports:financial', token, filters),
    receipt: (token, settlementId) => ipcRenderer.invoke('reports:receipt', token, settlementId),
    csv: (token, filters) => ipcRenderer.invoke('reports:csv', token, filters),
    xlsx: (token, filters) => ipcRenderer.invoke('reports:xlsx', token, filters),
    savePdf: (token, filters) => ipcRenderer.invoke('reports:pdf', token, filters),
    print: (token, filters) => ipcRenderer.invoke('reports:print', token, filters),
    saveReceiptPdf: (token, settlementId) => ipcRenderer.invoke('reports:receipt-pdf', token, settlementId),
    printReceipt: (token, settlementId) => ipcRenderer.invoke('reports:receipt-print', token, settlementId),
  },
  backup: {
    list: (token, filters) => ipcRenderer.invoke('backup:list', token, filters),
    create: (token) => ipcRenderer.invoke('backup:create', token),
    verify: (token, filePath) => ipcRenderer.invoke('backup:verify', token, filePath),
    restoreSelect: (token) => ipcRenderer.invoke('backup:restore-select', token),
  },
  lan: {
    status: (token) => ipcRenderer.invoke('lan:status', token),
    configure: (token, input) => ipcRenderer.invoke('lan:configure', token, input),
    pairingCode: (token) => ipcRenderer.invoke('lan:pairing-code', token),
  },
  registry: {
    listCustomers: (token, filters) => ipcRenderer.invoke('registry:customers:list', token, filters),
    saveCustomer: (token, input) => ipcRenderer.invoke('registry:customers:save', token, input),
    setCustomerActive: (token, id, active) => ipcRenderer.invoke('registry:customers:set-active', token, id, active),
    listCreditors: (token, filters) => ipcRenderer.invoke('registry:creditors:list', token, filters),
    saveCreditor: (token, input) => ipcRenderer.invoke('registry:creditors:save', token, input),
    setCreditorActive: (token, id, active) => ipcRenderer.invoke('registry:creditors:set-active', token, id, active),
    listCategories: (token, filters) => ipcRenderer.invoke('registry:categories:list', token, filters),
    saveCategory: (token, input) => ipcRenderer.invoke('registry:categories:save', token, input),
    setCategoryActive: (token, id, active) => ipcRenderer.invoke('registry:categories:set-active', token, id, active),
  },
});

contextBridge.exposeInMainWorld('financeiroPlanning', {
  listCostCenters: (token, filters) => ipcRenderer.invoke('planning:cost-centers:list', token, filters),
  saveCostCenter: (token, input) => ipcRenderer.invoke('planning:cost-centers:save', token, input),
  listTags: (token, filters) => ipcRenderer.invoke('planning:tags:list', token, filters),
  saveTag: (token, input) => ipcRenderer.invoke('planning:tags:save', token, input),
  getAllocations: (token, entryId) => ipcRenderer.invoke('planning:allocations:get', token, entryId),
  setAllocations: (token, entryId, allocations) => ipcRenderer.invoke('planning:allocations:set', token, entryId, allocations),
  getEntryTags: (token, entryId) => ipcRenderer.invoke('planning:entry-tags:get', token, entryId),
  setEntryTags: (token, entryId, tagIds) => ipcRenderer.invoke('planning:entry-tags:set', token, entryId, tagIds),
  listScenarios: (token, filters) => ipcRenderer.invoke('planning:scenarios:list', token, filters),
  saveScenario: (token, input) => ipcRenderer.invoke('planning:scenarios:save', token, input),
  listBudgets: (token, filters) => ipcRenderer.invoke('planning:budgets:list', token, filters),
  saveBudget: (token, input) => ipcRenderer.invoke('planning:budgets:save', token, input),
  compareBudget: (token, filters) => ipcRenderer.invoke('planning:budgets:compare', token, filters),
  listGoals: (token, filters) => ipcRenderer.invoke('planning:goals:list', token, filters),
  saveGoal: (token, input) => ipcRenderer.invoke('planning:goals:save', token, input),
  listAttachments: (token, entryId) => ipcRenderer.invoke('planning:attachments:list', token, entryId),
  addAttachment: (token, entryId, input) => ipcRenderer.invoke('planning:attachments:add', token, entryId, input),
  reviewAttachment: (token, id) => ipcRenderer.invoke('planning:attachments:review', token, id),
  runAttachmentOcr: (token, id) => ipcRenderer.invoke('planning:attachments:ocr', token, id),
  listApprovalPolicies: (token, filters) => ipcRenderer.invoke('planning:approval-policies:list', token, filters),
  saveApprovalPolicy: (token, input) => ipcRenderer.invoke('planning:approval-policies:save', token, input),
  listApprovals: (token, filters) => ipcRenderer.invoke('planning:approvals:list', token, filters),
  requestApproval: (token, input) => ipcRenderer.invoke('planning:approvals:request', token, input),
  decideApproval: (token, requestId, input) => ipcRenderer.invoke('planning:approvals:decide', token, requestId, input),
  runBulk: (token, input) => ipcRenderer.invoke('planning:bulk', token, input),
  projection: (token, input) => ipcRenderer.invoke('planning:projection', token, input),
});
