import { useCallback, useEffect, useState } from 'react';
import { brl } from '../lib/format';

type Props = { token: string };
export default function DrePage({ token }: Props) {
  const api = window.financeiro!; const planning=window.financeiroPlanning!;
  const [year,setYear] = useState(new Date().getFullYear());
  const [basis,setBasis] = useState<'realized'|'accrual'>('realized');
  const [costCenterId,setCostCenterId]=useState(''); const [tagId,setTagId]=useState('');
  const [centers,setCenters]=useState<PlanningCostCenter[]>([]); const [tags,setTags]=useState<PlanningTag[]>([]);
  const [dre,setDre] = useState<DreReport | null>(null);
  const [error,setError] = useState('');
  useEffect(()=>{Promise.all([planning.listCostCenters(token),planning.listTags(token)]).then(([nextCenters,nextTags])=>{setCenters(nextCenters);setTags(nextTags);}).catch((err)=>setError(err instanceof Error?err.message:String(err)));},[planning,token]);
  const reload = useCallback(async()=>{try{const filters:Record<string,unknown>={from:`${year}-01-01`,to:`${year}-12-31`,basis};if(costCenterId)filters.costCenterId=costCenterId;if(tagId)filters.tagId=tagId;const dreCall=api.analytics.dre as unknown as (token:string,filters:Record<string,unknown>)=>Promise<DreReport>;setDre(await dreCall(token,filters));setError('');}catch(err){setError(err instanceof Error?err.message:String(err));}},[api,token,year,basis,costCenterId,tagId]);
  useEffect(()=>{void reload();},[reload]);
  return <section className="page-stack"><div className="page-header"><div><p className="eyebrow">DRE</p><h2>Demonstração de resultado</h2><p className="muted">Visão realizada por baixas ou competência por vencimento, com filtros de centro de custo e tag.</p></div><label className="year-control">Ano<input type="number" value={year} onChange={(e)=>setYear(Number(e.target.value))}/></label></div>{error&&<div className="error-box">{error}</div>}<div className="panel report-toolbar"><label>Centro de custo<select value={costCenterId} onChange={(e)=>setCostCenterId(e.target.value)}><option value="">Todos</option>{centers.map((center)=><option key={center.id} value={center.id}>{center.code} · {center.name}</option>)}</select></label><label>Tag<select value={tagId} onChange={(e)=>setTagId(e.target.value)}><option value="">Todas</option>{tags.map((tag)=><option key={tag.id} value={tag.id}>{tag.name}</option>)}</select></label></div><div className="segmented"><button className={basis==='realized'?'active':''} onClick={()=>setBasis('realized')}>Realizado</button><button className={basis==='accrual'?'active':''} onClick={()=>setBasis('accrual')}>Competência</button></div><div className="metric-grid"><div className="metric-card"><span>Receita</span><strong>{brl(dre?.totals.revenueCents||0)}</strong></div><div className="metric-card"><span>Despesa</span><strong>{brl(dre?.totals.expenseCents||0)}</strong></div><div className="metric-card"><span>Resultado</span><strong>{brl(dre?.totals.resultCents||0)}</strong></div><div className="metric-card"><span>Margem</span><strong>{dre?.totals.revenueCents?`${((dre.totals.resultCents/dre.totals.revenueCents)*100).toFixed(1)}%`:'0,0%'}</strong></div></div><div className="panel table-panel"><table><thead><tr><th>Grupo DRE</th><th>Receitas</th><th>Despesas</th><th>Resultado</th></tr></thead><tbody>{dre?.groups.map((item)=><tr key={item.group}><td><strong>{item.group}</strong></td><td>{brl(item.revenueCents)}</td><td>{brl(item.expenseCents)}</td><td>{brl(item.resultCents)}</td></tr>)}</tbody></table>{!dre?.groups.length&&<div className="empty-state">Sem movimentação no período.</div>}</div></section>;
}