import { FormEvent, useCallback, useEffect, useState } from 'react';
import { Pause, Play, Plus, RefreshCcw } from 'lucide-react';
import { brl, can, toCents, today } from '../lib/format';

type Props = { token:string; session:FinanceiroSession };
export default function RecurringPage({token,session}:Props){
  const api=window.financeiro!; const editable=can(session,'finance.manage');
  const [kind,setKind]=useState<FinanceiroKind>('PAYABLE'); const [rules,setRules]=useState<RecurringRule[]>([]); const [accounts,setAccounts]=useState<FinanceAccount[]>([]); const [categories,setCategories]=useState<FinancialCategory[]>([]); const [parties,setParties]=useState<PartyRecord[]>([]); const [error,setError]=useState('');
  const [form,setForm]=useState({description:'',amount:'',startDate:today(),dueDay:String(new Date().getDate()),maxOccurrences:'',accountId:'',categoryId:'',counterpartyId:''});
  const reload=useCallback(async()=>{try{const [nextRules,nextAccounts,nextCategories,nextParties]=await Promise.all([api.recurrence.list(token),api.finance.listAccounts(token),api.registry.listCategories(token,{nature:kind==='PAYABLE'?'EXPENSE':'REVENUE'}),kind==='PAYABLE'?api.registry.listCreditors(token):api.registry.listCustomers(token)]);setRules(nextRules);setAccounts(nextAccounts);setCategories(nextCategories);setParties(nextParties);setError('');}catch(err){setError(err instanceof Error?err.message:String(err));}},[api,token,kind]);
  useEffect(()=>{void reload();},[reload]); useEffect(()=>setForm((old)=>({...old,categoryId:'',counterpartyId:''})),[kind]);
  async function create(event:FormEvent){event.preventDefault();try{await api.recurrence.create(token,{kind,description:form.description,amountCents:toCents(form.amount),startDate:form.startDate,dueDay:Number(form.dueDay),maxOccurrences:form.maxOccurrences?Number(form.maxOccurrences):null,accountId:form.accountId||null,categoryId:form.categoryId||null,...(kind==='PAYABLE'?{creditorId:form.counterpartyId||null}:{customerId:form.counterpartyId||null})});setForm({...form,description:'',amount:'',maxOccurrences:'',categoryId:'',counterpartyId:''});await reload();}catch(err){setError(err instanceof Error?err.message:String(err));}}
  async function toggle(rule:RecurringRule){try{await api.recurrence.setActive(token,rule.id,!rule.active);await reload();}catch(err){setError(err instanceof Error?err.message:String(err));}}
  async function generate(){try{await api.recurrence.generate(token,today());await reload();}catch(err){setError(err instanceof Error?err.message:String(err));}}
  return <section className="page-stack"><div className="page-header"><div><p className="eyebrow">Recorrências</p><h2>Contas automáticas</h2><p className="muted">Geração idempotente de mensalidades, contratos e despesas fixas.</p></div>{editable&&<button className="secondary-button" onClick={()=>void generate()}><RefreshCcw size={16}/> Gerar até hoje</button>}</div>{error&&<div className="error-box">{error}</div>}
    {editable&&<form className="panel form-grid" onSubmit={create}><h3><Plus size={18}/> Nova recorrência</h3><label>Tipo<select value={kind} onChange={(e)=>setKind(e.target.value as FinanceiroKind)}><option value="PAYABLE">A pagar</option><option value="RECEIVABLE">A receber</option></select></label><label className="wide">Descrição<input required value={form.description} onChange={(e)=>setForm({...form,description:e.target.value})}/></label><label>Valor<input required value={form.amount} onChange={(e)=>setForm({...form,amount:e.target.value})} placeholder="0,00"/></label><label>Início<input type="date" required value={form.startDate} onChange={(e)=>setForm({...form,startDate:e.target.value})}/></label><label>Dia do vencimento<input type="number" min="1" max="31" required value={form.dueDay} onChange={(e)=>setForm({...form,dueDay:e.target.value})}/></label><label>Nº ocorrências<input type="number" min="1" value={form.maxOccurrences} onChange={(e)=>setForm({...form,maxOccurrences:e.target.value})} placeholder="Sem limite"/></label><label>Conta<select value={form.accountId} onChange={(e)=>setForm({...form,accountId:e.target.value})}><option value="">Não definida</option>{accounts.map((x)=><option key={x.id} value={x.id}>{x.name}</option>)}</select></label><label>Categoria<select value={form.categoryId} onChange={(e)=>setForm({...form,categoryId:e.target.value})}><option value="">Sem categoria</option>{categories.map((x)=><option key={x.id} value={x.id}>{x.name}</option>)}</select></label><label>{kind==='PAYABLE'?'Credor':'Cliente'}<select value={form.counterpartyId} onChange={(e)=>setForm({...form,counterpartyId:e.target.value})}><option value="">Não informado</option>{parties.map((x)=><option key={x.id} value={x.id}>{x.name}</option>)}</select></label><button className="primary-button">Salvar recorrência</button></form>}
    <div className="panel table-panel"><table><thead><tr><th>Descrição</th><th>Tipo</th><th>Valor</th><th>Próximo</th><th>Geradas</th><th>Status</th><th></th></tr></thead><tbody>{rules.map((rule)=><tr key={rule.id}><td><strong>{rule.description}</strong></td><td>{rule.kind==='PAYABLE'?'Pagar':'Receber'}</td><td>{brl(rule.amountCents)}</td><td>{rule.nextDueAt}</td><td>{rule.generatedCount}{rule.maxOccurrences?` / ${rule.maxOccurrences}`:''}</td><td><span className={`badge ${rule.active?'badge-settled':'badge-cancelled'}`}>{rule.active?'ATIVA':'PAUSADA'}</span></td><td>{editable&&<button className="secondary-button small" onClick={()=>void toggle(rule)}>{rule.active?<Pause size={14}/>:<Play size={14}/>} {rule.active?'Pausar':'Ativar'}</button>}</td></tr>)}</tbody></table>{rules.length===0&&<div className="empty-state">Nenhuma recorrência cadastrada.</div>}</div>
  </section>;
}
