/// <reference types="vite/client" />

declare global {
  type FinanceiroRole = 'ADMIN' | 'FINANCE' | 'MANAGER' | 'READONLY';
  type FinanceiroKind = 'PAYABLE' | 'RECEIVABLE';
  type CategoryNature = 'REVENUE' | 'EXPENSE';
  type CashDirection = 'IN' | 'OUT';
  type CashMovementType = 'OPENING' | 'DEPOSIT' | 'WITHDRAWAL' | 'TRANSFER' | 'ADJUSTMENT' | 'SETTLEMENT';
  type StatementSourceType = 'CSV' | 'OFX' | 'PDF' | 'MANUAL';

  interface FinanceiroUser { id:string; login:string; name:string; role:FinanceiroRole; active:boolean; createdAt?:string; updatedAt?:string }
  interface FinanceiroSession { user:FinanceiroUser; permissions:string[] }
  interface FinanceiroHealth { ok:boolean; storage:'sqlite'; userVersion:number; path:string }
  interface FinanceAccount { id:string; name:string; type:'CASH'|'BANK'|'CARD'|'OTHER'; active:boolean }
  interface FinanceSettlement { id:string; entryId:string; accountId?:string|null; amountCents:number; method?:string|null; note?:string|null; occurredAt:string; createdAt:string; reversedAt?:string|null }
  interface FinanceEntry { id:string; kind:FinanceiroKind; description:string; categoryId?:string|null; accountId?:string|null; customerId?:string|null; creditorId?:string|null; amountCents:number; issueAt?:string|null; dueAt:string; status:'OPEN'|'PARTIAL'|'SETTLED'|'CANCELLED'; sourceType?:string|null; sourceId?:string|null; notes?:string|null; recurrenceRuleId?:string|null; recurrenceKey?:string|null; settledCents:number; openCents:number; isOverdue:boolean; settlements:FinanceSettlement[] }
  interface FinancialSummary { payableTotalCents:number; payableSettledCents:number; payableOpenCents:number; receivableTotalCents:number; receivableSettledCents:number; receivableOpenCents:number; overduePayableCents:number; overdueReceivableCents:number }
  interface PartyRecord { id:string; name:string; document?:string|null; phone?:string|null; email?:string|null; notes?:string|null; active:boolean }
  interface FinancialCategory { id:string; name:string; nature:CategoryNature; dreGroup:string; active:boolean }
  interface CashflowMovement { id:string; accountId:string; direction:CashDirection; type:CashMovementType; amountCents:number; occurredAt:string; note?:string|null; transferId?:string|null; sourceType:'MANUAL'|'SETTLEMENT'; sourceId?:string|null; createdAt:string }
  interface AccountBalance { id:string; name:string; type:FinanceAccount['type']; active:boolean; balanceCents:number }
  interface CashflowSummary { openingBalanceCents:number; inCents:number; outCents:number; netCents:number; closingBalanceCents:number }
  interface DreGroup { group:string; revenueCents:number; expenseCents:number; resultCents:number }
  interface DreReport { basis:'realized'|'accrual'; from:string; to:string; groups:DreGroup[]; totals:{revenueCents:number;expenseCents:number;resultCents:number} }
  interface FinancialIndicators extends FinancialSummary { receivedCents:number; paidCents:number; resultCents:number; bankBalanceCents:number; totalBalanceCents:number }
  interface DashboardSnapshot { year:number; range:{from:string;to:string}; cards:FinancialIndicators; accountBalances:AccountBalance[]; monthly:Array<{month:string;inCents:number;outCents:number;netCents:number}>; topExpenses:Array<{description:string;amountCents:number}>; dre:DreReport }
  interface RecurringRule { id:string; kind:FinanceiroKind; description:string; categoryId?:string|null; accountId?:string|null; customerId?:string|null; creditorId?:string|null; amountCents:number; startDate:string; endDate?:string|null; dueDay:number; intervalMonths:number; maxOccurrences?:number|null; generatedCount:number; nextDueAt:string; notes?:string|null; active:boolean; createdAt:string; updatedAt:string }

  interface StatementClassification { matched:boolean; ruleId:string|null; confidence:number; reason:string; assignments?:Record<string,unknown> }
  interface StatementCanonicalTransaction { id:string; accountId:string; date:string; description:string; amountCents:number; direction:'credit'|'debit'; counterparty?:string; normalized?:string; category?:string; sourceFingerprint:string; businessFingerprint:string; classification:StatementClassification }
  interface StatementPreview { sourceType:StatementSourceType; documentId:string; transactions:StatementCanonicalTransaction[]; duplicates:StatementCanonicalTransaction[]; summary:{parsed:number;accepted:number;duplicates:number;classified:number;needsReview:number} }
  interface StatementStoredTransaction { id:string; batch_id:string; account_id:string; account_name:string; occurred_at:string; description:string; normalized_description:string; counterparty?:string|null; amount_cents:number; direction:'credit'|'debit'; category_label?:string|null; source_fingerprint:string; business_fingerprint:string; rule_id?:string|null; rule_reason?:string|null; rule_confidence:number; review_status:'PENDING'|'AUTO_CLASSIFIED'|'REVIEWED'|'MATCHED'; created_at:string }
  interface StatementInput { sourceType:StatementSourceType; accountId:string; documentId?:string; filename?:string; content?:string; text?:string; dataBase64?:string; rows?:Array<Record<string,unknown>>; rules?:Array<Record<string,unknown>> }
  interface StatementSuggestion { transactionId:string; allocations:Array<{obligationId:string;amountCents:number}>; confidence:number; kind:string; reason:string; evidence?:Record<string,unknown> }
  interface StatementTransferSuggestions { internalTransfers:Array<Record<string,unknown>>; withdrawals:Array<Record<string,unknown>>; returns:Array<Record<string,unknown>>; matchedTransactionIds:string[] }

  interface WorkspaceItem { name:string; path:string; parentPath:string; type:'folder'|'file'; extension:string; size:number; modifiedAt:string; createdAt:string }
  interface WorkspaceListing { path:string; parentPath:string; items:WorkspaceItem[] }
  interface WorkspaceTreeNode { name:string; path:string; children:WorkspaceTreeNode[] }
  interface WorkspaceTrashItem { id:string; name:string; originalPath:string; storedName?:string; deletedAt:string; type:'folder'|'file' }
  interface WorkspacePreferences { viewMode:'list'|'grid'; sortBy:'name'|'modifiedAt'|'size'|'type'; sortDirection:'asc'|'desc' }

  interface FinanceAlert { key:string; type:'DUE_TODAY'|'OVERDUE'|'LOW_BALANCE'|'INTERNAL'; severity:'INFO'|'WARNING'|'CRITICAL'; title:string; body:string; entityType:string; entityId:string; amountCents?:number; thresholdCents?:number; dueAt?:string; state?:'READ'|'DISMISSED'|null; read:boolean; dismissed:boolean }
  interface AlertThreshold { accountId:string; accountName:string; thresholdCents:number; enabled:boolean; updatedAt?:string }
  interface FinancialReportRow { id:string; dueAt:string; kind:FinanceiroKind; description:string; status:string; amountCents:number; settledCents:number; openCents:number; isOverdue:boolean; account:string; category:string; counterparty:string }
  interface FinancialReport { kind:'FINANCIAL_REPORT'; generatedAt:string; filters:Record<string,unknown>; rows:FinancialReportRow[]; totals:{amountCents:number;settledCents:number;openCents:number}; indicators?:FinancialIndicators }
  interface SettlementReceipt { kind:'SETTLEMENT_RECEIPT'; title:string; number:string; generatedAt:string; entry:{id:string;kind:FinanceiroKind;description:string;amountCents:number}; settlement:{id:string;amountCents:number;method?:string|null;occurredAt:string;note?:string|null}; counterparty?:{id:string;name:string;document?:string|null}|null; account?:{id:string;name:string;type:string}|null; category?:{id:string;name:string;nature:string;dreGroup:string}|null }
  interface BackupRecord { id:string; kind:'MANUAL'|'AUTO'|'PRE_MIGRATION'|'PRE_RESTORE'; path:string; sha256:string; bytes:number; schema_version?:number; schemaVersion?:number; status?:string; created_at?:string; createdAt?:string; verified_at?:string|null }
  interface LanStatus { enabled:boolean; host:string; port:number; updatedAt?:string|null; running:boolean; address?:{host:string;port:number}|null; urls:string[] }
  interface LanPairingCode { id:string; code:string; expiresAt:string }

  interface Window {
    financeiro?: {
      system:{ health():Promise<FinanceiroHealth> };
      auth:{ needsBootstrap():Promise<boolean>; bootstrap(input:{name?:string;password:string}):Promise<FinanceiroUser>; login(login:string,password:string):Promise<{token:string;expiresAt:number;user:FinanceiroUser;permissions:string[]}>; session(token:string):Promise<FinanceiroSession>; logout(token:string):Promise<void>; listUsers(token:string):Promise<FinanceiroUser[]>; createUser(token:string,input:{name:string;login:string;password:string;role:FinanceiroRole}):Promise<FinanceiroUser>; setUserActive(token:string,userId:string,active:boolean):Promise<FinanceiroUser> };
      finance:{ listAccounts(token:string,filters?:{includeInactive?:boolean}):Promise<FinanceAccount[]>; createAccount(token:string,input:{name:string;type:FinanceAccount['type']}):Promise<FinanceAccount>; listEntries(token:string,filters?:Record<string,unknown>):Promise<FinanceEntry[]>; createEntry(token:string,input:Record<string,unknown>):Promise<FinanceEntry>; settleEntry(token:string,entryId:string,input:{amountCents:number;method?:string;occurredAt?:string;accountId?:string}):Promise<{settlement:FinanceSettlement;entry:FinanceEntry}>; reverseSettlement(token:string,settlementId:string,reason:string):Promise<{settlement:FinanceSettlement;entry:FinanceEntry}>; cancelEntry(token:string,entryId:string,reason:string):Promise<FinanceEntry>; summary(token:string,filters?:Record<string,unknown>):Promise<FinancialSummary> };
      statements:{ preview(token:string,input:StatementInput):Promise<StatementPreview>; commit(token:string,input:StatementInput):Promise<{batchId:string;inserted:number;duplicates:number;summary:StatementPreview['summary']}>; list(token:string,filters?:Record<string,unknown>):Promise<StatementStoredTransaction[]>; suggestTransfers(token:string,filters?:Record<string,unknown>):Promise<StatementTransferSuggestions>; suggestEntries(token:string,filters?:Record<string,unknown>):Promise<StatementSuggestion[]>; decision(token:string,input:{transactionId:string;entryId:string;decision:'accepted'|'rejected'|'manual';amountCents?:number}):Promise<{transactionId:string;entryId:string;decision:string;stats:{accepted:number;rejected:number;manual:number}}> };
      workspace:{ list(token:string,path?:string):Promise<WorkspaceListing>; tree(token:string):Promise<WorkspaceTreeNode>; search(token:string,query:string):Promise<WorkspaceItem[]>; listTrash(token:string):Promise<WorkspaceTrashItem[]>; preferences(token:string):Promise<WorkspacePreferences>; setPreferences(token:string,input:Partial<WorkspacePreferences>):Promise<WorkspacePreferences>; createFolder(token:string,parentPath:string,name:string):Promise<WorkspaceItem>; createFile(token:string,parentPath:string,name:string,content?:string):Promise<WorkspaceItem>; importFiles(token:string,targetPath:string):Promise<{canceled:boolean;items:WorkspaceItem[]}>; importDropped(token:string,targetPath:string,files:File[]):Promise<WorkspaceItem[]>; rename(token:string,path:string,name:string):Promise<WorkspaceItem>; move(token:string,path:string,targetPath:string):Promise<WorkspaceItem>; copy(token:string,path:string,targetPath:string):Promise<WorkspaceItem>; trash(token:string,path:string):Promise<WorkspaceTrashItem>; restore(token:string,id:string):Promise<WorkspaceItem>; deleteForever(token:string,id:string):Promise<boolean>; open(token:string,path:string):Promise<{opened:boolean;reason?:string}>; reveal(token:string,path:string):Promise<{revealed:boolean;reason?:string}> };
      cashflow:{ listMovements(token:string,filters?:{from?:string;to?:string;accountId?:string}):Promise<CashflowMovement[]>; createMovement(token:string,input:{accountId:string;type:Exclude<CashMovementType,'TRANSFER'|'SETTLEMENT'>;direction?:CashDirection;amountCents:number;occurredAt?:string;note?:string}):Promise<CashflowMovement>; transfer(token:string,input:{fromAccountId:string;toAccountId:string;amountCents:number;occurredAt?:string;note?:string}):Promise<{transferId:string;out:CashflowMovement;in:CashflowMovement}>; balances(token:string,filters?:{asOf?:string;includeInactive?:boolean}):Promise<AccountBalance[]>; summary(token:string,filters?:{from?:string;to?:string;accountId?:string}):Promise<CashflowSummary> };
      analytics:{ dre(token:string,filters?:{from?:string;to?:string;basis?:'realized'|'accrual'}):Promise<DreReport>; indicators(token:string,filters?:Record<string,unknown>):Promise<FinancialIndicators>; dashboard(token:string,filters?:{year?:number}):Promise<DashboardSnapshot> };
      recurrence:{ list(token:string,filters?:{includeInactive?:boolean}):Promise<RecurringRule[]>; create(token:string,input:Record<string,unknown>):Promise<RecurringRule>; setActive(token:string,id:string,active:boolean):Promise<RecurringRule>; generate(token:string,asOf:string):Promise<FinanceEntry[]> };
      alerts:{ list(token:string,filters?:{asOf?:string;includeDismissed?:boolean}):Promise<FinanceAlert[]>; acknowledge(token:string,alertKey:string,state:'READ'|'DISMISSED'):Promise<{alertKey:string;userId:string;state:string}>; listThresholds(token:string):Promise<AlertThreshold[]>; setThreshold(token:string,accountId:string,thresholdCents:number,enabled:boolean):Promise<AlertThreshold>; saveInternal(token:string,input:{id?:string;title:string;body?:string;severity?:'INFO'|'WARNING'|'CRITICAL';startsAt?:string;endsAt?:string;active?:boolean}):Promise<Record<string,unknown>> };
      reports:{ financial(token:string,filters?:Record<string,unknown>):Promise<FinancialReport>; receipt(token:string,settlementId:string):Promise<SettlementReceipt>; csv(token:string,filters?:Record<string,unknown>):Promise<{filename:string;mime:string;data:string}>; xlsx(token:string,filters?:Record<string,unknown>):Promise<{filename:string;mime:string;dataBase64:string}>; savePdf(token:string,filters?:Record<string,unknown>):Promise<{canceled:boolean;path?:string;bytes?:number}>; print(token:string,filters?:Record<string,unknown>):Promise<{printed:boolean}>; saveReceiptPdf(token:string,settlementId:string):Promise<{canceled:boolean;path?:string;bytes?:number}>; printReceipt(token:string,settlementId:string):Promise<{printed:boolean}> };
      backup:{ list(token:string,filters?:Record<string,unknown>):Promise<BackupRecord[]>; create(token:string):Promise<BackupRecord>; verify(token:string,filePath:string):Promise<{valid:boolean;reason:string;sha256?:string;bytes?:number;schemaVersion?:number}>; restoreSelect(token:string):Promise<{canceled:boolean;restored?:boolean;restarting?:boolean;safetyBackup?:string}> };
      lan:{ status(token:string):Promise<LanStatus>; configure(token:string,input:{enabled:boolean;host:string;port:number}):Promise<LanStatus>; pairingCode(token:string):Promise<LanPairingCode> };
      registry:{ listCustomers(token:string,filters?:Record<string,unknown>):Promise<PartyRecord[]>; saveCustomer(token:string,input:Partial<PartyRecord>&{name:string}):Promise<PartyRecord>; setCustomerActive(token:string,id:string,active:boolean):Promise<PartyRecord>; listCreditors(token:string,filters?:Record<string,unknown>):Promise<PartyRecord[]>; saveCreditor(token:string,input:Partial<PartyRecord>&{name:string}):Promise<PartyRecord>; setCreditorActive(token:string,id:string,active:boolean):Promise<PartyRecord>; listCategories(token:string,filters?:{nature?:CategoryNature;includeInactive?:boolean}):Promise<FinancialCategory[]>; saveCategory(token:string,input:Partial<FinancialCategory>&{name:string;nature:CategoryNature}):Promise<FinancialCategory>; setCategoryActive(token:string,id:string,active:boolean):Promise<FinancialCategory> };
    };
  }
}

export {};
